packages:
  - apps/*
  - packages/*
  - tools/*
  - workers/*

patchedDependencies:
  '@scryfall/api-types@1.0.0-alpha.4': patches/@scryfall__api-types@1.0.0-alpha.4.patch
catalogs:
  cli:
    '@antfu/eslint-config': ^4.14.1
    '@prettier/plugin-xml': ^3.4.1
    eslint: ^9.29.0
    eslint-config-turbo: ^2.5.4
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    unbuild: ^3.5.0
    wrangler: ^4.21.2
  core:
    turbo: ^2.5.4
  nuxt:
    '@nuxt/eslint': ^1.3.0
    '@nuxt/image': ^1.10.0
    '@nuxt/test-utils': ^3.19.1
    '@nuxt/ui-pro': ^3.1.3
    '@nuxthub/core': ^0.9.0
    '@pinia/nuxt': ^0.11.1
    '@vueuse/core': ^13.3.0
    '@vueuse/nuxt': ^13.3.0
    nuxt: ^3.16.2
    pinia: ^3.0.3
    vue: ^3.5.13
    vue-router: ^4.5.0
    vue-tsc: ^2.2.10
  testing:
    '@vue/test-utils': ^2.4.6
    happy-dom: ^17.6.3
    playwright-core: ^1.52.0
    vitest: ^3.2.2
  tools:
    '@hono/zod-validator': ^0.2.1
    chart.js: ^4.5.0
    cheerio: ^1.0.0-rc.12
    defu: ^6.1.4
    hono: ^4.4.0
    nanoid: ^5.1.5
    socket.io: ^4.8.1
    socket.io-client: ^4.8.1
    vue-chartjs: ^5.3.2
    zod: ^3.25.56
  types:
    '@scryfall/api-types': 1.0.0-alpha.4
    '@types/node': ^22.13.10

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd
